### ISSUE TITLE
json文件格式错了

### ISSUE THREAD

**Issue by CaffuChin0** [MinatoAquaCrews/nonebot_plugin_crazy_thursday#20]
系统：Ubuntu

版本：v0.2.6

报错代码：
```
03-27 16:47:34 [ERROR] uvicorn | Traceback (most recent call last):
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 648, in startup
    await handler()
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.10/lib/python3.10/site-packages/nonebot_plugin_crazy_thursday/config.py", line 54, in post_check
    docs: Dict[str, Union[float, List[str]]] = response.json()
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.10/lib/python3.10/site-packages/httpx/_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)   
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

03-27 16:47:34 [ERROR] uvicorn | Application startup failed. Exiting.
```

重新下一个json丢进去一样报错，目前先暂时uninstall了。

**Comment by KafCoppelia** [comment]
是 `raw.fastgit.org` 域名换了，导致资源下载失败……
